# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 64785f89ed731e6f43c1a67c60dc3ada2df4941bd759098b1513189d7c4ebcfe12cd092b2a61c06d9a96af038b049f3f354cfb6a65bea4a7bad915f6b5680e27

test:
  secret_key_base: f691f8f4bc61a28a5e5aff4d5d74dd550acbe98214a231a6187ae6bd4b8676240a15f719d6d0facf310cbf417386a3164cbac5b62b533c74b6738bdc6f30b446

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
